name: Script/Command not working
description: Report a script/command not working
labels: ["not working"]
body:
  - type: markdown
    attributes:
      value: |
        ### Please provide details about the issue you're experiencing
        Fill in the following information to help us diagnose the problem.
        
  - type: textarea
    attributes:
      label: Logs
      description: Please paste relevant logs or error messages
      placeholder: |
        Paste logs here...
        (Include timestamps if available)
    validations:
      required: true
      
  - type: input
    attributes:
      label: Terminal Name
      description: Name of the terminal application
      placeholder: e.g., Termux, JuiceSSH, etc.
    validations:
      required: true
      
  - type: input
    attributes:
      label: Terminal Version
      description: Version of the terminal application
      placeholder: e.g., 1.2.3
    validations:
      required: true
      
  - type: input
    attributes:
      label: Android Version
      description: Version of Android you're using
      placeholder: e.g., 13, 12, 11, etc.
    validations:
      required: true
      
  - type: input
    attributes:
      label: Device
      description: Your device model
      placeholder: e.g., Samsung Galaxy S23, Pixel 7, etc.
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Type
      description: Select the type of issue
      options:
        - Crash
        - Performance
        - UI/UX
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional Information
      description: Any other details that might be helpful
      placeholder: Describe what you were doing when the issue occurred...
